package cli

import (
	"io/fs"
	"os"
	"path/filepath"
	"testing"

	"github.com/mvanhorn/cli-printing-press/v4/internal/pipeline"
	"github.com/mvanhorn/cli-printing-press/v4/internal/version"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func writeMiniModule(t *testing.T, root string, files map[string]string) {
	t.Helper()
	require.NoError(t, os.MkdirAll(root, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(root, "go.mod"), []byte("module mini\n\ngo 1.22\n"), 0o644))
	for rel, body := range files {
		path := filepath.Join(root, rel)
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
		require.NoError(t, os.WriteFile(path, []byte(body), 0o644))
	}
}

func generatedCLIFile(body string) string {
	return "// Generated by CLI Printing Press. DO NOT EDIT.\npackage cli\n\n" + body
}

func generatedClientFile(body string) string {
	return "// Generated by CLI Printing Press. DO NOT EDIT.\npackage client\n\n" + body
}

// Two-way merge of a helper rename (no synthesized base): fresh promoted
// callers must win so a dangling old helper call cannot ship.
func TestFinalizeForceMergeDropsVersionBumpHelperRenamePreserve(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	snapshotDir := filepath.Join(dir, "mini.preserve-1")
	freshDir := filepath.Join(dir, "mini")

	writeMiniModule(t, snapshotDir, map[string]string{
		"internal/cli/old_helpers.go": generatedCLIFile("func oldHelper() string { return \"old\" }\n"),
		"internal/cli/promoted.go":    generatedCLIFile("func Promoted() string { return oldHelper() }\n"),
		"internal/cli/novel.go":       "package cli\n\nfunc NovelKeep() string { return \"kept\" }\n",
	})
	writeMiniModule(t, freshDir, map[string]string{
		"internal/cli/helpers.go":  generatedCLIFile("func newHelper() string { return \"new\" }\n"),
		"internal/cli/promoted.go": generatedCLIFile("func Promoted() string { return newHelper() }\n"),
	})

	require.NoError(t, finalizeForceMerge(snapshotDir, freshDir, nil, true, func() error { return nil }, false))

	promoted, err := os.ReadFile(filepath.Join(freshDir, "internal", "cli", "promoted.go"))
	require.NoError(t, err)
	assert.Contains(t, string(promoted), "newHelper",
		"version-bump helper rename must keep the fresh promoted caller")
	assert.NotContains(t, string(promoted), "oldHelper",
		"two-way merge must not preserve a dangling old helper call")
	assert.NoFileExists(t, filepath.Join(freshDir, "internal", "cli", "old_helpers.go"),
		"fresh generation dropped the old helper file; rematch must not rehydrate it")

	novel, err := os.ReadFile(filepath.Join(freshDir, "internal", "cli", "novel.go"))
	require.NoError(t, err)
	assert.Contains(t, string(novel), "NovelKeep",
		"novel files must survive the build-break rematch")

	require.NoError(t, compileGeneratedTree(freshDir))
}

// A same-spec templated addition that still builds must survive merge.
func TestFinalizeForceMergePreservesCompilingHandEdits(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	snapshotDir := filepath.Join(dir, "mini.preserve-1")
	freshDir := filepath.Join(dir, "mini")

	writeMiniModule(t, snapshotDir, map[string]string{
		"internal/cli/root.go": generatedCLIFile("func Execute() {}\n\nfunc HandEdit() string { return \"kept\" }\n"),
	})
	writeMiniModule(t, freshDir, map[string]string{
		"internal/cli/root.go": generatedCLIFile("func Execute() {}\n"),
	})

	require.NoError(t, finalizeForceMerge(snapshotDir, freshDir, nil, true, func() error { return nil }, false))

	got, err := os.ReadFile(filepath.Join(freshDir, "internal", "cli", "root.go"))
	require.NoError(t, err)
	assert.Contains(t, string(got), "HandEdit",
		"compiling same-spec hand-edits must still be preserved")
	require.NoError(t, compileGeneratedTree(freshDir))
}

func TestFinalizeForceMergeSameVersionWithoutOriginalTakesFreshSharedBody(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	snapshotDir := filepath.Join(dir, "mini.preserve-1")
	freshDir := filepath.Join(dir, "mini")

	writeMiniModule(t, snapshotDir, map[string]string{
		".printing-press.json":      `{"schema_version":2,"printing_press_version":"` + version.Version + `","api_name":"mini","cli_name":"mini-pp-cli"}`,
		"internal/client/client.go": generatedClientFile("func Shared() string { return \"stale\" }\n"),
		"internal/cli/novel.go":     "package cli\n\nfunc NovelKeep() string { return \"kept\" }\n",
	})
	writeMiniModule(t, freshDir, map[string]string{
		"internal/client/client.go": generatedClientFile("func Shared() string { return \"fresh\" }\n"),
	})

	require.NoError(t, finalizeForceMerge(snapshotDir, freshDir, nil, true, func() error { return nil }, false))

	got, err := os.ReadFile(filepath.Join(freshDir, "internal", "client", "client.go"))
	require.NoError(t, err)
	assert.Contains(t, string(got), `return "fresh"`,
		"without a synthesizable original, same-version force must not overlay a stale shared body")
	assert.NotContains(t, string(got), `return "stale"`)

	novel, err := os.ReadFile(filepath.Join(freshDir, "internal", "cli", "novel.go"))
	require.NoError(t, err)
	assert.Contains(t, string(novel), "NovelKeep")
	require.NoError(t, compileGeneratedTree(freshDir))
}

func TestFinalizeForceMergeReplacesRewrittenBodyOnVersionBumpWithoutBase(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	snapshotDir := filepath.Join(dir, "mini.preserve-1")
	freshDir := filepath.Join(dir, "mini")

	oldClient := "// Generated by CLI Printing Press. DO NOT EDIT.\npackage client\n\nfunc credentialAppliesToURL(u string) bool { return u != \"\" }\n"
	newClient := "// Generated by CLI Printing Press. DO NOT EDIT.\npackage client\n\nfunc credentialAppliesToURL(u string) bool { return u == \"https://bound.example\" }\n"
	writeMiniModule(t, snapshotDir, map[string]string{
		".printing-press.json":      `{"schema_version":2,"printing_press_version":"0.0.1","api_name":"mini","cli_name":"mini-pp-cli"}`,
		"internal/client/client.go": oldClient,
		"internal/cli/novel.go":     "package cli\n\nfunc NovelKeep() string { return \"kept\" }\n",
	})
	writeMiniModule(t, freshDir, map[string]string{
		"internal/client/client.go": newClient,
	})

	require.NoError(t, finalizeForceMerge(snapshotDir, freshDir, nil, true, func() error { return nil }, false))

	got, err := os.ReadFile(filepath.Join(freshDir, "internal", "client", "client.go"))
	require.NoError(t, err)
	assert.Contains(t, string(got), `u == "https://bound.example"`,
		"version-bump reprint without a synthesized base must still replace the older generated body")
	assert.NotContains(t, string(got), `u != ""`)

	novel, err := os.ReadFile(filepath.Join(freshDir, "internal", "cli", "novel.go"))
	require.NoError(t, err)
	assert.Contains(t, string(novel), "NovelKeep")
	require.NoError(t, compileGeneratedTree(freshDir))
}

func TestFinalizeForceMergeSkipsVanishedFreshTreeEntry(t *testing.T) {
	dir := t.TempDir()
	snapshotDir := filepath.Join(dir, "mini.preserve-1")
	freshDir := filepath.Join(dir, "mini")

	writeMiniModule(t, snapshotDir, map[string]string{
		"internal/cli/novel.go": "package cli\n\nfunc NovelKeep() string { return \"implemented\" }\n",
	})
	writeMiniModule(t, freshDir, map[string]string{
		"internal/cli/novel.go": "package cli\n\nfunc NovelKeep() string { return \"TODO scaffold\" }\n",
	})
	gotmp := filepath.Join(freshDir, ".gotmp")
	require.NoError(t, os.MkdirAll(gotmp, 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(gotmp, "x"), []byte("tmp"), 0o644))

	clear := pipeline.SetCopyDirWalkHookForTest(func(path string, _ fs.DirEntry) {
		if path == gotmp {
			require.NoError(t, os.RemoveAll(path))
		}
	})
	t.Cleanup(clear)

	require.NoError(t, finalizeForceMerge(snapshotDir, freshDir, nil, false, nil, false))

	novel, err := os.ReadFile(filepath.Join(freshDir, "internal", "cli", "novel.go"))
	require.NoError(t, err)
	assert.Contains(t, string(novel), "implemented")
	assert.NotContains(t, string(novel), "TODO scaffold")
}
