// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package client

import (
	"fmt"
	"net/url"
	"regexp"
	"sort"
	"strings"
)

// templateVarPattern matches {placeholder} occurrences in a URL. The character
// class mirrors the placeholder names emitted by the spec parser
// (lowercase ASCII identifiers) and intentionally rejects nested braces or
// punctuation so an unrelated literal { in a URL — query payloads pasted
// verbatim, for example — is left alone.
var templateVarPattern = regexp.MustCompile(`\{([a-zA-Z_][a-zA-Z0-9_]*)\}`)

// templateVarEnvNames maps each placeholder declared in
// APISpec.EndpointTemplateVars to the environment variable that resolves it.
// The mapping is fixed at generate time so request-time substitution can
// produce an actionable error ("export SHOPIFY_SHOP=...") without consulting
// the spec. Placeholders that escape into a URL but aren't in this map fall
// back to a generic "template variable {x} unresolved" message.
var templateVarEnvNames = map[string]string{
	"tenant": "TENANT_ID",
}

var globalPathTemplateVars = map[string]bool{
	"tenant": true,
}

// buildURL concatenates baseURL and path, then substitutes every {placeholder}
// against vars. vars is normally Config.TemplateVars, populated from env at
// Load() time.
//
// Both BaseURL and path may carry placeholders — Shopify's BaseURL
// "https://{shop}" combines with GraphQLEndpointPath
// "/admin/api/{version}/graphql.json", and a single helper avoids two passes
// of replacement scattered across the request methods. When any placeholder
// remains unresolved the function returns a TemplateVarError naming the env
// var the user should export.
func buildURL(baseURL, path string, vars map[string]string) (string, error) {
	full := baseURL + path
	if !templateVarPattern.MatchString(full) {
		return full, nil
	}
	seen := map[string]bool{}
	var unresolved []string
	resolve := func(raw string, pathContext bool) string {
		return templateVarPattern.ReplaceAllStringFunc(raw, func(match string) string {
			key := match[1 : len(match)-1]
			if v, ok := vars[key]; ok && v != "" {
				if pathContext && globalPathTemplateVars[key] {
					return url.PathEscape(v)
				}
				return v
			}
			if !seen[key] {
				seen[key] = true
				unresolved = append(unresolved, key)
			}
			return match
		})
	}
	resolved := resolve(baseURL, false) + resolve(path, true)
	if len(unresolved) == 0 {
		return resolved, nil
	}
	sort.Strings(unresolved)
	return "", &TemplateVarError{Names: unresolved}
}

// TemplateVarError reports unresolved {var} placeholders detected at request
// time. The message names the env var(s) the user needs to export — not just
// the placeholder — because the placeholder ("shop") is implementation
// vocabulary while the env var ("SHOPIFY_SHOP") is what they will actually
// type into a shell.
type TemplateVarError struct {
	Names []string
}

// Registered {placeholder}s in an auth endpoint are substituted before the
// request is dialed, so a brace is never treated as a hostname. Values that
// fill a path segment are percent-encoded so a slash in the value cannot
// add another path segment. Host labels stay unescaped.
func ResolveTemplateURL(raw string, vars map[string]string) (string, error) {
	if !templateVarPattern.MatchString(raw) {
		return raw, nil
	}
	suffix := ""
	base := raw
	if i := strings.IndexAny(raw, "?#"); i >= 0 {
		suffix = raw[i:]
		base = raw[:i]
	}
	authority, path := splitAuthURLAuthority(base)
	resolvedAuthority, err := buildURL(authority, "", vars)
	if err != nil {
		return "", err
	}
	pathVars := vars
	if templateVarPattern.MatchString(path) {
		pathVars = pathEscapedAuthVars(path, vars)
	}
	resolvedPath, err := buildURL("", path, pathVars)
	if err != nil {
		return "", err
	}
	resolvedSuffix := suffix
	if templateVarPattern.MatchString(suffix) {
		resolvedSuffix, err = buildURL(suffix, "", vars)
		if err != nil {
			return "", err
		}
	}
	return resolvedAuthority + resolvedPath + resolvedSuffix, nil
}

func splitAuthURLAuthority(raw string) (string, string) {
	prefix := ""
	rest := raw
	if i := strings.Index(raw, "://"); i >= 0 {
		prefix = raw[:i+3]
		rest = raw[i+3:]
	}
	if j := strings.Index(rest, "/"); j >= 0 {
		return prefix + rest[:j], rest[j:]
	}
	return prefix + rest, ""
}

func pathEscapedAuthVars(path string, vars map[string]string) map[string]string {
	escaped := make(map[string]string, len(vars))
	for key, value := range vars {
		escaped[key] = value
	}
	for _, match := range templateVarPattern.FindAllStringSubmatch(path, -1) {
		if len(match) < 2 {
			continue
		}
		key := match[1]
		if value, ok := escaped[key]; ok && value != "" {
			// The path argument is substituted with path escaping already
			// enabled for promoted global path vars. Encoding those values
			// here would turn a single slash into %252F.
			if globalPathTemplateVars[key] {
				continue
			}
			escaped[key] = url.PathEscape(value)
		}
	}
	return escaped
}
func (e *TemplateVarError) Error() string {
	parts := make([]string, 0, len(e.Names))
	for _, name := range e.Names {
		if env := templateVarEnvNames[name]; env != "" {
			parts = append(parts, fmt.Sprintf("%s not set; export %s=<value>", env, env))
			continue
		}
		parts = append(parts, fmt.Sprintf("template variable {%s} unresolved", name))
	}
	return strings.Join(parts, "; ")
}
