package regenmerge

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/mvanhorn/cli-printing-press/v4/internal/pipeline"
)

// TestMergeIntoFreshTreePreservesValueDrift exercises a templated
// config.go const literal change — TEMPLATED-VALUE-DRIFT must preserve
// the snapshot-side literal even when decl-sets match.
func TestMergeIntoFreshTreeOverlaysHandEditKeepsFreshRewrite(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	base := filepath.Join(t.TempDir(), "base")
	rel := filepath.Join("internal", "client", "client.go")
	header := "// Generated by CLI Printing Press. DO NOT EDIT.\npackage client\n\n"
	write := func(root, body string) {
		require.NoError(t, os.MkdirAll(filepath.Join(root, filepath.Dir(rel)), 0o755))
		require.NoError(t, os.WriteFile(filepath.Join(root, rel), []byte(header+body), 0o644))
	}
	write(base, `func credentialAppliesToURL(u string) bool { return u != "" }
func HandPatched() string { return "orig" }
`)
	write(snap, `func credentialAppliesToURL(u string) bool { return u != "" }
func HandPatched() string { return "kept" }
`)
	write(fresh, `func credentialAppliesToURL(u string) bool { return u == "https://bound.example" }
func HandPatched() string { return "fresh" }
`)

	report, err := Classify(snap, fresh, Options{Force: true, BaseDir: base})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true, BaseDir: base}))

	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.Contains(t, string(got), `u == "https://bound.example"`,
		"reprint must replace the still-compiling older generated body")
	assert.Contains(t, string(got), `return "kept"`,
		"hand-edited decl in the same file must survive")
	assert.NotContains(t, string(got), `return "fresh"`,
		"fresh must not overwrite the hand-edited decl")
}

func TestMergeIntoFreshTreeTakesFreshBodiesAndKeepsHandAdditionsWithoutBase(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "client", "client.go")
	header := "// Generated by CLI Printing Press. DO NOT EDIT.\npackage client\n\n"
	write := func(root, body string) {
		require.NoError(t, os.MkdirAll(filepath.Join(root, filepath.Dir(rel)), 0o755))
		require.NoError(t, os.WriteFile(filepath.Join(root, rel), []byte(header+body), 0o644))
	}
	write(snap, `func credentialAppliesToURL(u string) bool { return u != "" }
func HandAdded() string { return "kept" }
`)
	write(fresh, `func credentialAppliesToURL(u string) bool { return u == "https://bound.example" }
`)

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	src := string(got)
	assert.Contains(t, src, `u == "https://bound.example"`,
		"two-way merge must take fresh templated bodies")
	assert.NotContains(t, src, `u != ""`)
	assert.Contains(t, src, `return "kept"`,
		"hand-authored novel decls must still overlay onto fresh")
}

func TestMergeIntoFreshTreeRefreshesWhichGo(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join("internal", "cli", "which.go")
	header := "// Generated by CLI Printing Press. DO NOT EDIT.\npackage cli\n\n"
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte(header+"var whichIndex = []string{\"old cmd\"}\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(header+"var whichIndex = []string{\"new cmd\"}\n"), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.Contains(t, string(got), "new cmd")
	assert.NotContains(t, string(got), "old cmd")
}

func TestMergeIntoFreshTreePreservesValueDrift(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := "internal/config/config.go"
	templated := func(literal string) []byte {
		return []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package config

const authPrefix = "` + literal + `"
`)
	}
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "config"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "config"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), templated("Token "), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), templated("Bearer "), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.Contains(t, string(got), `"Token "`,
		"hand-edited literal must survive merge into fresh tree")
	assert.Empty(t, FormatSkippedTemplatedHandEdits(report),
		"same-spec preserve must not report applied templated edits as dropped")
}

// TestMergeIntoFreshTreePreservesDeclSetAdditions covers hand-authored
// functions added to a templated client file — TEMPLATED-WITH-ADDITIONS
// must preserve the snapshot.
func TestMergeIntoFreshTreePreservesDeclSetAdditions(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := "internal/client/queries.go"
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "client"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "client"), 0o755))

	pubBody := []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package client

const placeholderQuery = ""

func GetTransactions() string { return "transactions" }
func GetCategories() string { return "categories" }
`)
	freshBody := []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package client

const placeholderQuery = ""
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), pubBody, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), freshBody, 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.Contains(t, string(got), "GetTransactions", "added function survives")
	assert.Contains(t, string(got), "GetCategories", "added function survives")
}

func TestMergeIntoFreshTreePrunesFreshDeclCollidingWithPreservedFile(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "cli"), 0o755))

	rootRel := "internal/cli/root.go"
	snapRoot := []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli

var version = "1.0.0"

func Execute() {}
func customRootHook() {}
func newVersionCliCmd() string { return version }
`)
	freshRoot := []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli

func Execute() {}
`)
	freshVersion := []byte(`package cli

var version = "1.0.0"

func newVersionCmd() string { return version }
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, rootRel), snapRoot, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rootRel), freshRoot, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "cli", "version.go"), freshVersion, 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	assert.NoFileExists(t, filepath.Join(fresh, "internal", "cli", "version.go"),
		"legacy root.go version layout must not gain a split-out version.go on reprint")

	gotRoot, err := os.ReadFile(filepath.Join(fresh, rootRel))
	require.NoError(t, err)
	assert.Contains(t, string(gotRoot), "customRootHook",
		"the hand-edited root file is still preserved")
	assert.Contains(t, string(gotRoot), `var version = "1.0.0"`,
		"the published runtime version value stays in root.go")
}

func TestPreserveMCPMainVersionValuesRemovesFreshVarWhenSnapshotHasNoMCPVersion(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, "internal", "cli", "root.go"), []byte(`package cli

var version = "1.2.3"
`), 0o644))
	staleRel := "cmd/stale-pp-mcp/main.go"
	currentRel := "cmd/current-pp-mcp/main.go"
	for _, rel := range []string{staleRel, currentRel} {
		require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
		require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	}
	require.NoError(t, os.WriteFile(filepath.Join(snap, staleRel), []byte(`package main

func main() {}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, staleRel), []byte(`package main

var version = "2.0.0"

func main() {
	_ = version
}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(snap, currentRel), []byte(`package main

var version = "1.2.3"
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, currentRel), []byte(`package main

var version = "2.0.0"
`), 0o644))

	report := &MergeReport{Files: []FileClassification{
		{Path: staleRel},
		{Path: currentRel},
	}}
	require.NoError(t, preserveMCPMainVersionValues(snap, fresh, report))

	got, err := os.ReadFile(filepath.Join(fresh, currentRel))
	require.NoError(t, err)
	assert.Contains(t, string(got), `var version = "1.2.3"`,
		"a missing snapshot version in one MCP file must not skip later MCP files")
	got, err = os.ReadFile(filepath.Join(fresh, staleRel))
	require.NoError(t, err)
	assert.NotContains(t, string(got), `var version =`)
	assert.Contains(t, string(got), `_ = "1.2.3"`)
}

func TestPreserveMCPMainVersionValuesFallsBackToFreshLiteral(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := "cmd/stale-pp-mcp/main.go"
	require.NoError(t, os.MkdirAll(filepath.Join(snap, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, filepath.Dir(rel)), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte(`package main

func main() {}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(`package main

var version = "2.0.0"

func main() {
	_ = version
}
`), 0o644))

	report := &MergeReport{Files: []FileClassification{{Path: rel}}}
	require.NoError(t, preserveMCPMainVersionValues(snap, fresh, report))

	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.NotContains(t, string(got), `var version =`)
	assert.Contains(t, string(got), `_ = "2.0.0"`)
}

func TestInlineStringVarReferencesAndRemoveSkipsLocalBindings(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	path := filepath.Join(dir, "main.go")
	require.NoError(t, os.WriteFile(path, []byte(`package main

var version = "0.0.0-dev"

func mcpVersion() string { return "local" }

func localParameter(version string) string {
	return version
}

func localShortDecl() string {
	version := mcpVersion()
	return version
}

func main() {
	_ = version
}
`), 0o644))

	require.NoError(t, inlineStringVarReferencesAndRemove(path, "version", `"1.2.3"`))

	got, err := os.ReadFile(path)
	require.NoError(t, err)
	gotSrc := string(got)
	assert.NotContains(t, gotSrc, `var version =`)
	assert.Contains(t, gotSrc, `func localParameter(version string) string`)
	assert.Contains(t, gotSrc, `version := mcpVersion()`)
	assert.Contains(t, gotSrc, `_ = "1.2.3"`)
}

func TestMergeIntoFreshTreePrunesOnlyCollidingNameFromMultiNameValueSpec(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "cli"), 0o755))

	require.NoError(t, os.WriteFile(filepath.Join(snap, "internal", "cli", "root.go"), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli

var version = "1.0.0"
func customRootHook() {}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "cli", "root.go"), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "cli", "version.go"), []byte(`package cli

var version, buildChannel = "1.0.0", "stable"
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	gotVersion, err := os.ReadFile(filepath.Join(fresh, "internal", "cli", "version.go"))
	require.NoError(t, err)
	assert.NotContains(t, string(gotVersion), "version,")
	assert.NotContains(t, string(gotVersion), `"1.0.0"`)
	assert.Contains(t, string(gotVersion), "buildChannel")
	assert.Contains(t, string(gotVersion), `"stable"`)
}

func TestMergeIntoFreshTreeLeavesIotaConstBlockWhenCollisionWouldShiftValues(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "cli"), 0o755))

	require.NoError(t, os.WriteFile(filepath.Join(snap, "internal", "cli", "root.go"), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli

const Bar = 99
func customRootHook() {}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "cli", "root.go"), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "cli", "constants.go"), []byte(`package cli

const (
	Foo = iota
	Bar
	Baz
)
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	gotConstants, err := os.ReadFile(filepath.Join(fresh, "internal", "cli", "constants.go"))
	require.NoError(t, err)
	assert.Contains(t, string(gotConstants), "Foo = iota")
	assert.Contains(t, string(gotConstants), "Bar")
	assert.Contains(t, string(gotConstants), "Baz",
		"the whole const block must stay intact rather than shifting inherited iota values")
}

func TestMergeIntoFreshTreeLeavesImplicitConstBlockWhenCollisionWouldOrphanValue(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "cli"), 0o755))

	require.NoError(t, os.WriteFile(filepath.Join(snap, "internal", "cli", "root.go"), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli

const Version = "1.0.0"
func customRootHook() {}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "cli", "root.go"), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "cli", "constants.go"), []byte(`package cli

const (
	Version = "1.0.0"
	DefaultVersion
)
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	gotConstants, err := os.ReadFile(filepath.Join(fresh, "internal", "cli", "constants.go"))
	require.NoError(t, err)
	assert.Contains(t, string(gotConstants), `Version = "1.0.0"`)
	assert.Contains(t, string(gotConstants), "DefaultVersion",
		"implicit const repetition must not be orphaned by pruning its explicit predecessor")
}

func TestMergeIntoFreshTreePrunesUnusedImportAfterFreshDeclCollision(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "cli"), 0o755))

	require.NoError(t, os.WriteFile(filepath.Join(snap, "internal", "cli", "root.go"), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli

var version = "1.0.0"
func customRootHook() {}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "cli", "root.go"), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "cli", "version.go"), []byte(`package cli

import (
	"fmt"
	"strings"
)

var version = fmt.Sprint("1.0.0")

func buildChannel() string {
	return strings.ToUpper("stable")
}
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	gotVersion, err := os.ReadFile(filepath.Join(fresh, "internal", "cli", "version.go"))
	require.NoError(t, err)
	assert.NotContains(t, string(gotVersion), `"fmt"`,
		"imports used only by pruned declarations should be removed")
	assert.Contains(t, string(gotVersion), `"strings"`,
		"imports still used by surviving declarations should remain")
	assert.Contains(t, string(gotVersion), "strings.ToUpper")
}

func TestMergeIntoFreshTreePreservesStoreExtrasEdits(t *testing.T) {
	t.Parallel()

	snap, fresh, rel := writeStoreExtrasFixture(t)
	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	assertStoreExtrasMigrationPreserved(t, fresh, rel)
}

func TestMergeIntoFreshTreeNovelOnlyPreservesStoreExtrasEdits(t *testing.T) {
	t.Parallel()

	snap, fresh, rel := writeStoreExtrasFixture(t)
	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true, NovelOnly: true}))

	assertStoreExtrasMigrationPreserved(t, fresh, rel)
	assert.Empty(t, FormatSkippedTemplatedHandEdits(report),
		"editable-hook extras.go preserved under NovelOnly must not be listed as dropped")
}

func writeStoreExtrasFixture(t *testing.T) (string, string, string) {
	t.Helper()

	snap, fresh := makeMergeFixture(t)
	rel := "internal/store/extras.go"
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "store"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "store"), 0o755))

	freshBody := []byte(`package store

import (
	"context"
	"database/sql"
	"fmt"
)

func (s *Store) migrateExtras(ctx context.Context, conn *sql.Conn) error {
	migrations := []string{
		// Add CREATE TABLE IF NOT EXISTS statements here.
	}
	for _, m := range migrations {
		if _, err := conn.ExecContext(ctx, m); err != nil {
			return fmt.Errorf("extra migration failed: %w", err)
		}
	}
	return nil
}
`)
	snapBody := []byte(`package store

import (
	"context"
	"database/sql"
	"fmt"
)

func (s *Store) migrateExtras(ctx context.Context, conn *sql.Conn) error {
	migrations := []string{
		` + "`" + `CREATE TABLE IF NOT EXISTS novel_events (id TEXT PRIMARY KEY)` + "`" + `,
	}
	for _, m := range migrations {
		if _, err := conn.ExecContext(ctx, m); err != nil {
			return fmt.Errorf("extra migration failed: %w", err)
		}
	}
	return nil
}
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), snapBody, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), freshBody, 0o644))

	return snap, fresh, rel
}

func assertStoreExtrasMigrationPreserved(t *testing.T, fresh, rel string) {
	t.Helper()
	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.Contains(t, string(got), "novel_events",
		"agent-authored store extras migrations must survive regen merge")
}

// TestMergeIntoFreshTreeReinjectsLostAddCommand covers a hand-added
// cmd.AddCommand line in a parent-command file — LostRegistrations must
// re-inject the call into the freshly emitted host.
func TestMergeIntoFreshTreeReinjectsLostAddCommand(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "cli"), 0o755))

	rel := "internal/cli/transactions.go"
	pubBody := []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

func newTransactionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{}
	cmd.AddCommand(newTransactionsListCmd(flags))
	cmd.AddCommand(newHandAddedCmd(flags))
	return cmd
}
`)
	freshBody := []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

func newTransactionsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{}
	cmd.AddCommand(newTransactionsListCmd(flags))
	return cmd
}
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), pubBody, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), freshBody, 0o644))
	// Pub also has a hand-written constructor file so the referent-existence
	// check passes.
	novelRel := "internal/cli/hand_added.go"
	novel := []byte(`package cli

func newHandAddedCmd(flags *rootFlags) *cobra.Command { return nil }
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, novelRel), novel, 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.Contains(t, string(got), "newHandAddedCmd",
		"hand-added AddCommand must be re-injected into fresh's transactions.go")
	assert.Contains(t, string(got), "newTransactionsListCmd",
		"existing template-emitted AddCommand survives")

	// Novel constructor file preserved.
	novelGot, err := os.ReadFile(filepath.Join(fresh, novelRel))
	require.NoError(t, err)
	assert.Contains(t, string(novelGot), "newHandAddedCmd")
}

func TestMergeIntoFreshTreeNovelOnlyReinjectsLostNovelAddCommand(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	for _, dir := range []string{snap, fresh} {
		require.NoError(t, os.MkdirAll(filepath.Join(dir, "internal", "cli"), 0o755))
	}

	rootRel := "internal/cli/root.go"
	pubRoot := []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

func Execute() {
	rootCmd := &cobra.Command{Use: "root"}
	rootCmd.AddCommand(newGeneratedCmd())
	rootCmd.AddCommand(newHandAddedCmd())
}
`)
	freshRoot := []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

func Execute() {
	rootCmd := &cobra.Command{Use: "root"}
	rootCmd.AddCommand(newCurrentCmd())
}
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, rootRel), pubRoot, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rootRel), freshRoot, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "cli", "generated.go"), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli

func newGeneratedCmd() *cobra.Command { return nil }
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "cli", "current.go"), []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli

func newCurrentCmd() *cobra.Command { return nil }
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(snap, "internal", "cli", "hand_added.go"), []byte(`package cli

func newHandAddedCmd() *cobra.Command { return nil }
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NotEmpty(t, report.LostRegistrations)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true, NovelOnly: true}))

	got, err := os.ReadFile(filepath.Join(fresh, rootRel))
	require.NoError(t, err)
	assert.Contains(t, string(got), "newHandAddedCmd",
		"NovelOnly force regen must preserve wiring for a preserved novel constructor")
	assert.NotContains(t, string(got), "newGeneratedCmd",
		"NovelOnly force regen must not restore a generated registration absent from fresh")
}

// TestMergeIntoFreshTreePreservesHandAuthoredCommandOnForceRegen proves the
// force-regeneration merge contract for independent command sources that
// intentionally live in a generated tree. The sources must be markerless:
// the generated marker means "stale template emission" and is correctly
// removed on regen. Their root registrations are additive so neither source
// can replace the other.
func TestMergeIntoFreshTreePreservesHandAuthoredCommandOnForceRegen(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	for _, dir := range []string{snap, fresh} {
		require.NoError(t, os.MkdirAll(filepath.Join(dir, "internal", "cli"), 0o755))
	}

	rootRel := "internal/cli/root.go"
	rootSrc := []byte(`// Generated by CLI Printing Press. DO NOT EDIT.
package cli

import cobra "example.invalid/regen/internal/fakecobra"

type rootFlags struct{}

var novelCommandHooks []func(root *cobra.Command, flags *rootFlags)

func registerNovelCommand(hook func(root *cobra.Command, flags *rootFlags)) {
	novelCommandHooks = append(novelCommandHooks, hook)
}

func newRootCmd(flags *rootFlags) *cobra.Command {
	rootCmd := &cobra.Command{Use: "root"}
	for _, hook := range novelCommandHooks { hook(rootCmd, flags) }
	rootCmd.AddCommand(newGeneratedCmd())
	return rootCmd
}


func RootCmd() *cobra.Command { return newRootCmd(&rootFlags{}) }

func newGeneratedCmd() *cobra.Command { return &cobra.Command{Use: "generated"} }
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, rootRel), rootSrc, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rootRel), rootSrc, 0o644))

	const offlineRel = "internal/cli/offline.go"
	require.NoError(t, os.WriteFile(filepath.Join(snap, offlineRel), []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
package cli

// Hand-authored generated-tree extension; keep this file markerless so the
// regen merge treats it as a preserved novel rather than stale output.
import cobra "example.invalid/regen/internal/fakecobra"

func newOfflineCmd() *cobra.Command { return &cobra.Command{Use: "offline"} }

func init() {
	registerNovelCommand(func(root *cobra.Command, flags *rootFlags) {
		root.AddCommand(newOfflineCmd())
	})
}
`), 0o644))
	const diagnosticsRel = "internal/cli/diagnostics.go"
	require.NoError(t, os.WriteFile(filepath.Join(snap, diagnosticsRel), []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
package cli

import cobra "example.invalid/regen/internal/fakecobra"

func newDiagnosticsCmd() *cobra.Command { return &cobra.Command{Use: "diagnostics"} }

func init() {
	registerNovelCommand(func(root *cobra.Command, flags *rootFlags) {
		root.AddCommand(newDiagnosticsCmd())
	})
}
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Equal(t, VerdictNovel, verdictMap(report)[offlineRel])
	assert.Equal(t, VerdictNovel, verdictMap(report)[diagnosticsRel])
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	offline, err := os.ReadFile(filepath.Join(fresh, offlineRel))
	require.NoError(t, err)
	assert.Contains(t, string(offline), "func newOfflineCmd()")
	diagnostics, err := os.ReadFile(filepath.Join(fresh, diagnosticsRel))
	require.NoError(t, err)
	assert.Contains(t, string(diagnostics), "func newDiagnosticsCmd()")
	root, err := os.ReadFile(filepath.Join(fresh, rootRel))
	require.NoError(t, err)
	assert.Contains(t, string(root), "novelCommandHooks = append(novelCommandHooks, hook)")
	assert.Contains(t, string(offline), "registerNovelCommand")
	assert.Contains(t, string(diagnostics), "registerNovelCommand")

	// Compile and execute the preserved sources as a real package, proving both
	// registrations survive force regen and attach commands to the built root.
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "go.mod"), []byte("module example.invalid/regen\n\ngo 1.23\n"), 0o644))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "fakecobra"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "fakecobra", "command.go"), []byte(`package fakecobra

import "fmt"

type Command struct {
	Use string
	children []*Command
}

func (c *Command) AddCommand(children ...*Command) { c.children = append(c.children, children...) }

func (c *Command) Find(args []string) (*Command, []string, error) {
	for _, child := range c.children {
		if child.Use == args[0] { return child, nil, nil }
	}
	return c, args, fmt.Errorf("command not found")
}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "internal", "cli", "root_hooks_test.go"), []byte(`package cli

import "testing"

func TestPreservedNovelCommandsCompose(t *testing.T) {
	root := RootCmd()
	for _, name := range []string{"offline", "diagnostics"} {
		if cmd, _, err := root.Find([]string{name}); err != nil || cmd == root {
			t.Fatalf("command %q unavailable: %v", name, err)
		}
	}
}
`), 0o644))
	cmd := exec.Command("go", "test", "./internal/cli", "-run", "TestPreservedNovelCommandsCompose")
	cmd.Dir = fresh
	output, err := cmd.CombinedOutput()
	require.NoErrorf(t, err, "compiled preservation fixture failed: %s", output)
}

// TestMergeIntoFreshTreeMergesGoModRequires exercises R9: hand-added
// require for novel-package deps survives.
func TestMergeIntoFreshTreeMergesGoModRequires(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	pubGoMod := []byte(`module example.com/snap

go 1.22

require (
	github.com/spf13/cobra v1.8.0
	modernc.org/sqlite v1.30.0
)
`)
	freshGoMod := []byte(`module example.com/snap

go 1.22

require (
	github.com/spf13/cobra v1.8.0
)
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, "go.mod"), pubGoMod, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "go.mod"), freshGoMod, 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	got, err := os.ReadFile(filepath.Join(fresh, "go.mod"))
	require.NoError(t, err)
	assert.Contains(t, string(got), "modernc.org/sqlite",
		"hand-added require must survive merge into fresh's go.mod")
}

func TestMergeIntoFreshTreeRewritesImportsAfterWritingMergedGoMod(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	pubGoMod := []byte(`module github.com/acme/library/demo-pp-cli

go 1.22

require (
	github.com/spf13/cobra v1.8.0
	modernc.org/sqlite v1.30.0
)
`)
	freshGoMod := []byte(`module demo-pp-cli

go 1.22

require github.com/spf13/cobra v1.8.0
`)
	const rel = "internal/cli/root.go"
	freshRoot := []byte(`package cli

import "demo-pp-cli/internal/client"

var _ = client.New
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, "go.mod"), pubGoMod, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, "go.mod"), freshGoMod, 0o644))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "cli"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), freshRoot, 0o644))

	report := &MergeReport{GoMod: &GoModMerge{}}
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	gotGoMod, err := os.ReadFile(filepath.Join(fresh, "go.mod"))
	require.NoError(t, err)
	assert.Contains(t, string(gotGoMod), "module github.com/acme/library/demo-pp-cli")
	assert.Contains(t, string(gotGoMod), "modernc.org/sqlite")

	gotRoot, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.Contains(t, string(gotRoot), `"github.com/acme/library/demo-pp-cli/internal/client"`)
	assert.NotContains(t, string(gotRoot), `"demo-pp-cli/internal/client"`)
	assert.True(t, report.GoMod.Merged)
}

// TestMergeIntoFreshTreeSweepsNonClassifiedFiles exercises R8: README and
// other non-Go files survive merge.
func TestMergeIntoFreshTreeSweepsNonClassifiedFiles(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	require.NoError(t, os.WriteFile(filepath.Join(snap, "README.md"), []byte("hand edited\n"), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(snap, "Makefile"), []byte("# custom\n"), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	got, err := os.ReadFile(filepath.Join(fresh, "README.md"))
	require.NoError(t, err)
	assert.Equal(t, "hand edited\n", string(got))

	got, err = os.ReadFile(filepath.Join(fresh, "Makefile"))
	require.NoError(t, err)
	assert.Equal(t, "# custom\n", string(got))
}

func TestMergeIntoFreshTreeSweepsMarkerlessFilesInGeneratorOwnedInternalDirs(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	handRel := filepath.Join("internal", "store", "retell_tables.sql")
	generatedRel := filepath.Join("internal", "store", "old_fixture.json")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "store"), 0o755))
	handAuthored := []byte("CREATE TABLE retell_calls (id TEXT PRIMARY KEY);\n")
	staleGenerated := []byte("// Generated by CLI Printing Press. DO NOT EDIT.\n{}\n")
	require.NoError(t, os.WriteFile(filepath.Join(snap, handRel), handAuthored, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(snap, generatedRel), staleGenerated, 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	got, err := os.ReadFile(filepath.Join(fresh, handRel))
	require.NoError(t, err)
	assert.Equal(t, string(handAuthored), string(got),
		"markerless standalone files under generated internal package dirs must survive force regen")
	assert.NoFileExists(t, filepath.Join(fresh, generatedRel),
		"missing generated-marker files under generated internal package dirs are stale output, not hand-authored files")
}

func TestMergeIntoFreshTreePreservesManuscripts(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := filepath.Join(".manuscripts", "20260523-171100", "research.json")
	path := filepath.Join(snap, rel)
	require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))
	require.NoError(t, os.WriteFile(path, []byte(`{"status":"accepted"}`), 0o640))
	wantModTime := time.Date(2026, 5, 23, 17, 11, 0, 0, time.UTC)
	require.NoError(t, os.Chtimes(path, wantModTime, wantModTime))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	gotPath := filepath.Join(fresh, rel)
	got, err := os.ReadFile(gotPath)
	require.NoError(t, err)
	assert.JSONEq(t, `{"status":"accepted"}`, string(got))

	info, err := os.Stat(gotPath)
	require.NoError(t, err)
	assert.Equal(t, os.FileMode(0o640), info.Mode().Perm())
	assert.True(t, info.ModTime().Equal(wantModTime), "mtime should survive force-regen sweep")
}

// TestMergeIntoFreshTreeNovelOnlySkipsValueDrift verifies that the
// cross-spec fallback path skips heuristic preservation.
func TestMergeIntoFreshTreeNovelOnlySkipsValueDrift(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := "internal/config/config.go"
	templated := func(literal string) []byte {
		return []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package config

const authPrefix = "` + literal + `"
`)
	}
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "config"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "config"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), templated("Token "), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), templated("Bearer "), 0o644))

	// Novel hand-written file should still survive in NovelOnly mode.
	novelRel := "internal/cli/handcrafted.go"
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, novelRel), []byte("package cli\n\nfunc Handcrafted() {}\n"), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true, NovelOnly: true}))

	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.Contains(t, string(got), `"Bearer "`,
		"NovelOnly mode keeps fresh's literal value (skips TEMPLATED-VALUE-DRIFT preservation)")

	novelGot, err := os.ReadFile(filepath.Join(fresh, novelRel))
	require.NoError(t, err)
	assert.Contains(t, string(novelGot), "Handcrafted",
		"NovelOnly preserves novel hand-written files")

	warning := FormatSkippedTemplatedHandEdits(report)
	assert.Contains(t, warning, "warning: cross-spec --force dropped hand-edits in generated files:")
	assert.Contains(t, warning, rel+" (TEMPLATED-VALUE-DRIFT)")
	assert.NotContains(t, warning, novelRel,
		"preserved novel files must not appear in the templated drop list")
}

func TestMergeIntoFreshTreeFailsClosedWhenRecordedCallSiteDropped(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	syncRel := filepath.Join("internal", "store", "sync.go")
	helperRel := filepath.Join("internal", "store", "envelope.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "store"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "store"), 0o755))

	snapSync := []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package store

func Sync(body []byte) {
	// pp:patch drop-envelope
	if guardAgainstErrorEnvelope(body) {
		return
	}
}
`)
	freshSync := []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package store

func Sync(body []byte) {}
`)
	helper := []byte(`package store

func guardAgainstErrorEnvelope(body []byte) bool { return len(body) > 0 && body[0] == '{' }
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, syncRel), snapSync, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, syncRel), freshSync, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(snap, helperRel), helper, 0o644))

	require.NoError(t, pipeline.EnsurePatchesDir(snap))
	require.NoError(t, pipeline.EnsurePatchesDir(fresh))
	record := []byte(`{
  "schema_version": 2,
  "id": "drop-envelope",
  "files": ["internal/store/sync.go", "internal/store/envelope.go"],
  "marker": "pp:patch drop-envelope",
  "call_sites": ["if guardAgainstErrorEnvelope("]
}
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, pipeline.PatchesDirName, "drop-envelope.json"), record, 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	err = MergeIntoFreshTree(snap, fresh, report, Options{Force: true, NovelOnly: true})
	require.Error(t, err)
	assert.Contains(t, err.Error(), `patch "drop-envelope"`)
	assert.Contains(t, err.Error(), "if guardAgainstErrorEnvelope(")
	assert.Contains(t, err.Error(), "absent from recorded files")

	_, statErr := os.Stat(filepath.Join(fresh, helperRel))
	assert.NoError(t, statErr, "the novel helper must survive; the dropped call site is the lie")
}

func TestMergeIntoFreshTreeHonorsIntactPatchRecords(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	syncRel := filepath.Join("internal", "store", "sync.go")
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "store"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "store"), 0o755))

	body := []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package store

func Sync(body []byte) {
	// pp:patch drop-envelope
	_ = guardAgainstErrorEnvelope
}

func guardAgainstErrorEnvelope(body []byte) bool { return false }
`)
	require.NoError(t, os.WriteFile(filepath.Join(snap, syncRel), body, 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, syncRel), body, 0o644))
	require.NoError(t, pipeline.EnsurePatchesDir(snap))
	require.NoError(t, pipeline.EnsurePatchesDir(fresh))
	require.NoError(t, os.WriteFile(filepath.Join(snap, pipeline.PatchesDirName, "drop-envelope.json"), []byte(`{
  "schema_version": 2,
  "id": "drop-envelope",
  "files": ["internal/store/sync.go"],
  "call_sites": ["guardAgainstErrorEnvelope"]
}
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))
	assert.FileExists(t, filepath.Join(fresh, pipeline.PatchesDirName, "drop-envelope.json"))
}

func TestMergeIntoFreshTreeNovelOnlyPreservesHandAuthoredNovelCommandTest(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := "internal/cli/call_test.go"
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "cli"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
// Novel command scaffold tests. Keep the wiring smoke test and add behavior cases as needed.

package cli

import "testing"

func TestNovelCallHelpWires(t *testing.T) {}

func TestNovelCallBehavior(t *testing.T) {
	if got := "real case"; got == "" {
		t.Fatal("missing assertion")
	}
}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// cli-printing-press: novel-scaffold-test
// Novel command scaffold tests. Keep the wiring smoke test and add behavior cases as needed.

package cli

import "testing"

func TestNovelCallHelpWires(t *testing.T) {}
`), 0o644))

	// This covers the old-to-new transition: the snapshot is an old DO NOT EDIT
	// scaffold with operator-authored tests, while the fresh file is the new
	// marker-based editable scaffold. Once both sides are markerless novel files,
	// the classifier returns VerdictNovel and preserves without this helper.
	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Equal(t, VerdictTemplatedWithAdditions, verdictMap(report)[rel])
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true, NovelOnly: true}))

	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.Contains(t, string(got), "TestNovelCallBehavior",
		"NovelOnly force-regen must preserve hand-authored tests replacing a markerless novel command scaffold")
}

func TestMergeIntoFreshTreeNovelOnlyPreservesHandAuthoredNovelCommandBody(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := "internal/cli/call.go"
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "cli"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Novel command scaffold. Implement the RunE body; generate --force preserves this file.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newNovelCallCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "call",
		Short: "Call an actor.",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			fmt.Fprintln(cmd.OutOrStdout(), "implemented")
			return nil
		},
	}
	return cmd
}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Novel command scaffold. Implement the RunE body; generate --force preserves this file.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newNovelCallCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "call",
		Short: "Call an actor.",
		Annotations: map[string]string{"mcp:read-only": "true"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if dryRunOK(flags) {
				return nil
			}
			return fmt.Errorf("TODO: implement novel feature %q", "call")
		},
	}
	return cmd
}
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true, NovelOnly: true}))

	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.Contains(t, string(got), `"implemented"`,
		"NovelOnly force-regen must preserve a hand-authored novel command body")
	assert.NotContains(t, string(got), "TODO: implement novel feature",
		"NovelOnly force-regen must not overwrite an implementation with the scaffold")
}

func TestMergeIntoFreshTreeNovelOnlyRefreshesUntouchedNovelCommandScaffold(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := "internal/cli/call.go"
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "cli"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Novel command scaffold. Implement the RunE body; generate --force preserves this file.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newNovelCallCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "call",
		Short: "Old scaffold text.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return fmt.Errorf("TODO: implement novel feature %q", "call")
		},
	}
	return cmd
}
`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Novel command scaffold. Implement the RunE body; generate --force preserves this file.

package cli

import (
	"fmt"

	"github.com/spf13/cobra"
)

func newNovelCallCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "call",
		Short: "Fresh scaffold text.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return fmt.Errorf("TODO: implement novel feature %q", "call")
		},
	}
	return cmd
}
`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true, NovelOnly: true}))

	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.Contains(t, string(got), "Fresh scaffold text.",
		"NovelOnly force-regen should keep fresh output for untouched scaffolds")
	assert.NotContains(t, string(got), "Old scaffold text.")
}

func TestMergeIntoFreshTreeNovelOnlyDoesNotPreserveOrdinaryGeneratedTestDrift(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := "internal/cli/root_test.go"
	templated := func(body string) []byte {
		return []byte(`// Copyright 2026 owner. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.
package cli

import "testing"

func TestRoot(t *testing.T) {
` + body + `
}
`)
	}
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	require.NoError(t, os.MkdirAll(filepath.Join(fresh, "internal", "cli"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(snap, rel), templated(`	t.Fatal("operator edit")`), 0o644))
	require.NoError(t, os.WriteFile(filepath.Join(fresh, rel), templated(`	t.Log("fresh generated test")`), 0o644))

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	assert.Equal(t, VerdictTemplatedBodyDrift, verdictMap(report)[rel])
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true, NovelOnly: true}))

	got, err := os.ReadFile(filepath.Join(fresh, rel))
	require.NoError(t, err)
	assert.Contains(t, string(got), "fresh generated test")
	assert.NotContains(t, string(got), "operator edit",
		"NovelOnly must not loosen DO NOT EDIT ownership for ordinary generated tests")
	assert.Contains(t, FormatSkippedTemplatedHandEdits(report), rel+" (TEMPLATED-BODY-DRIFT)")
}

func TestFormatSkippedTemplatedHandEdits(t *testing.T) {
	t.Parallel()

	assert.Empty(t, FormatSkippedTemplatedHandEdits(nil))
	assert.Empty(t, FormatSkippedTemplatedHandEdits(&MergeReport{}))

	report := &MergeReport{
		Files: []FileClassification{
			{Path: "internal/cli/root.go", Verdict: VerdictTemplatedClean},
			{Path: "internal/cli/z_flag.go", Verdict: VerdictTemplatedWithAdditions},
			{Path: "internal/cli/search.go", Verdict: VerdictTemplatedBodyDrift},
			{Path: "internal/config/config.go", Verdict: VerdictTemplatedValueDrift, Applied: true},
			{Path: "internal/cli/novel.go", Verdict: VerdictNovel, Applied: true},
			{Path: "internal/cli/stale.go", Verdict: VerdictPublishedOnlyTemplated},
		},
	}
	got := FormatSkippedTemplatedHandEdits(report)
	assert.Equal(t, ""+
		"warning: cross-spec --force dropped hand-edits in generated files:\n"+
		"  internal/cli/search.go (TEMPLATED-BODY-DRIFT)\n"+
		"  internal/cli/z_flag.go (TEMPLATED-WITH-ADDITIONS)\n", got)
}

func TestMergeIntoFreshTreePreservesGitMetadata(t *testing.T) {
	t.Parallel()

	for _, novelOnly := range []bool{false, true} {
		t.Run(fmt.Sprintf("novelOnly=%v", novelOnly), func(t *testing.T) {
			t.Parallel()

			snapRoot := `// Generated by CLI Printing Press. DO NOT EDIT.
package cli

func Execute() {}
`
			freshRoot := `// Generated by CLI Printing Press. DO NOT EDIT.
package cli

func Execute() {}
func newFreshCmd() {}
`
			gomod := "module example.com/force-git-preserve\n\ngo 1.22\n"
			gitmodules := "[submodule \"deps/example\"]\n\tpath = deps/example\n\turl = https://example.invalid/example.git\n"

			snap, fresh := makeMergeFixture(t)
			writeMergeFiles(t, snap, map[string]string{
				".gitmodules":          gitmodules,
				"go.mod":               gomod,
				"internal/cli/root.go": snapRoot,
			})
			writeMergeFiles(t, fresh, map[string]string{
				"go.mod":               gomod,
				"internal/cli/root.go": freshRoot,
			})

			runGit(t, snap, "init")
			runGit(t, snap, "config", "user.email", "force-merge@example.invalid")
			runGit(t, snap, "config", "user.name", "Force Merge Test")
			runGit(t, snap, "add", ".")
			runGit(t, snap, "commit", "-m", "initial")
			runGit(t, snap, "branch", "saved-history")
			runGit(t, snap, "tag", "v0.1.0")
			headBefore := strings.TrimSpace(runGit(t, snap, "rev-parse", "HEAD"))

			report, err := Classify(snap, fresh, Options{Force: true})
			require.NoError(t, err)
			require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true, NovelOnly: novelOnly}))

			assert.DirExists(t, filepath.Join(fresh, ".git"))
			assert.FileExists(t, filepath.Join(fresh, ".gitmodules"))
			assert.Contains(t, readFileString(t, filepath.Join(fresh, ".gitmodules")), "deps/example")
			assert.Equal(t, headBefore, strings.TrimSpace(runGit(t, fresh, "rev-parse", "HEAD")))
			assert.Equal(t, headBefore, strings.TrimSpace(runGit(t, fresh, "rev-parse", "refs/heads/saved-history")))
			assert.Equal(t, headBefore, strings.TrimSpace(runGit(t, fresh, "rev-parse", "refs/tags/v0.1.0")))
			assert.Contains(t, readFileString(t, filepath.Join(fresh, "internal", "cli", "root.go")), "newFreshCmd")
		})
	}
}

func TestMergeIntoFreshTreeDoesNotCreateGitMetadataForNonGitTree(t *testing.T) {
	t.Parallel()

	snapRoot := `// Generated by CLI Printing Press. DO NOT EDIT.
package cli

func Execute() {}
`
	freshRoot := `// Generated by CLI Printing Press. DO NOT EDIT.
package cli

func Execute() {}
func newFreshCmd() {}
`
	gomod := "module example.com/force-non-git\n\ngo 1.22\n"

	snap, fresh := makeMergeFixture(t)
	writeMergeFiles(t, snap, map[string]string{
		"go.mod":               gomod,
		"internal/cli/root.go": snapRoot,
	})
	writeMergeFiles(t, fresh, map[string]string{
		"go.mod":               gomod,
		"internal/cli/root.go": freshRoot,
	})

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	require.NoError(t, MergeIntoFreshTree(snap, fresh, report, Options{Force: true}))

	assert.NoDirExists(t, filepath.Join(fresh, ".git"))
	assert.NoFileExists(t, filepath.Join(fresh, ".git"))
	assert.Contains(t, readFileString(t, filepath.Join(fresh, "internal", "cli", "root.go")), "newFreshCmd")
}

func TestMergeIntoFreshTreeRefusesSymlinkedGitMetadata(t *testing.T) {
	t.Parallel()

	snapRoot := `// Generated by CLI Printing Press. DO NOT EDIT.
package cli

func Execute() {}
`
	freshRoot := `// Generated by CLI Printing Press. DO NOT EDIT.
package cli

func Execute() {}
func newFreshCmd() {}
`
	gomod := "module example.com/force-git-symlink\n\ngo 1.22\n"

	snap, fresh := makeMergeFixture(t)
	writeMergeFiles(t, snap, map[string]string{
		"go.mod":               gomod,
		"internal/cli/root.go": snapRoot,
	})
	writeMergeFiles(t, fresh, map[string]string{
		"go.mod":               gomod,
		"internal/cli/root.go": freshRoot,
	})

	outside := t.TempDir()
	if err := os.Symlink(outside, filepath.Join(snap, ".git")); err != nil {
		t.Skipf("symlink unavailable: %v", err)
	}

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	err = MergeIntoFreshTree(snap, fresh, report, Options{Force: true})
	require.Error(t, err)
	assert.Contains(t, strings.ToLower(err.Error()), "symlink")
	_, gitErr := os.Lstat(filepath.Join(fresh, ".git"))
	assert.True(t, os.IsNotExist(gitErr), "symlinked .git must not be copied into fresh")
}

// TestMergeIntoFreshTreeRefusesSnapshotSymlinks verifies symlink safety in
// the preserve path.
func TestMergeIntoFreshTreeRefusesSnapshotSymlinks(t *testing.T) {
	t.Parallel()

	snap, fresh := makeMergeFixture(t)
	rel := "internal/cli/sneaky.go"
	require.NoError(t, os.MkdirAll(filepath.Join(snap, "internal", "cli"), 0o755))
	target := filepath.Join(snap, "external.go")
	require.NoError(t, os.WriteFile(target, []byte("package cli\n"), 0o644))
	if err := os.Symlink(target, filepath.Join(snap, rel)); err != nil {
		t.Skipf("symlink unavailable: %v", err)
	}

	report, err := Classify(snap, fresh, Options{Force: true})
	require.NoError(t, err)
	err = MergeIntoFreshTree(snap, fresh, report, Options{Force: true})
	require.Error(t, err)
	assert.Contains(t, strings.ToLower(err.Error()), "symlink")
}

func makeMergeFixture(t *testing.T) (snap, fresh string) {
	t.Helper()
	dir := t.TempDir()
	snap = filepath.Join(dir, "snap")
	fresh = filepath.Join(dir, "fresh")
	require.NoError(t, os.MkdirAll(snap, 0o755))
	require.NoError(t, os.MkdirAll(fresh, 0o755))
	return snap, fresh
}

func writeMergeFiles(t *testing.T, root string, files map[string]string) {
	t.Helper()
	for rel, content := range files {
		full := filepath.Join(root, rel)
		require.NoError(t, os.MkdirAll(filepath.Dir(full), 0o755))
		require.NoError(t, os.WriteFile(full, []byte(content), 0o644))
	}
}
