// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newMediaPromotedCmd(flags *rootFlags) *cobra.Command {
	var bodyFile string

	cmd := &cobra.Command{
		Use:         "media",
		Short:       "Upload an input file",
		Long:        "Upload an input file",
		Example:     "  async-job-pp-cli media",
		Args:        cobra.NoArgs,
		Annotations: map[string]string{"pp:endpoint": "media.upload", "pp:method": "POST", "pp:path": "/media/upload"},
		RunE: func(cmd *cobra.Command, args []string) error {
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/media/upload"
			headerOverrides := map[string]string{
				"X-Printing-Press-Replay-Safe": "true",
			}

			params := map[string]string{}
			fields := map[string]string{}
			fileFields := map[string]string{}
			if cmd.Flags().Changed("file") || bodyFile != "" {
				fileFields["file"] = bodyFile
			}

			data, _, err := c.PostMultipartWithParamsAndHeaders(cmd.Context(), path, params, fields, fileFields, headerOverrides)
			if err != nil {
				return classifyAPIError(cmd.OutOrStdout(), err, flags)
			}
			outputData := data
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(outputData, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			formatData := data
			if flags.csv || flags.plain {
				formatData = outputData
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), formatData, flags, map[string]any{"source": "live"}, nil)
		},
	}
	cmd.Flags().StringVar(&bodyFile, "file", "", "File")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
