package generatedmarker

import (
	"bufio"
	"os"
	"strings"
)

// Text is the legacy classifier needle. The Go generated-file convention
// (`^// Code generated .* DO NOT EDIT\.$`) is case-sensitive and does not
// match this capital-G phrase, so emitted files carry both lines.
const Text = "Generated by CLI Printing Press"

// StandardText is the phrase inside StandardLine.
const StandardText = "Code generated by CLI Printing Press"

// StandardLine matches the Go generated-file convention.
const StandardLine = "// Code generated by CLI Printing Press. DO NOT EDIT."

// LegacyLine is the historical header classifiers already search for.
const LegacyLine = "// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT."

// FilePrefix is the two header lines emitted on generated source, StandardLine first.
func FilePrefix() string {
	return StandardLine + "\n" + LegacyLine + "\n"
}

// Contains reports whether s carries either generated-file marker.
func Contains(s string) bool {
	return strings.Contains(s, Text) || strings.Contains(s, StandardText)
}

// HasInFile reports whether one of the file's first few lines contains either marker.
func HasInFile(path string) bool {
	f, err := os.Open(path)
	if err != nil {
		return false
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	scanner.Buffer(make([]byte, 4096), 64*1024)
	for line := 0; line < 5 && scanner.Scan(); line++ {
		if Contains(scanner.Text()) {
			return true
		}
	}
	return false
}
