// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Code generated by CLI Printing Press. DO NOT EDIT.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

func newUsersCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "users",
		Short:       "Collection-level /users/email alongside item-level /users/{userId}/email.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:parent-group": "true", "pp:api-resource": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newUsersEmailCmd(flags))
	cmd.AddCommand(newUsersListCmd(flags))
	cmd.AddCommand(newUsersItemEmailCmd(flags))
	return cmd
}
