// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/spf13/cobra"
	"linear-pp-cli/internal/client"
	"linear-pp-cli/internal/cliutil"
	"linear-pp-cli/internal/store"
)

// syncResult holds the outcome of syncing a single resource.
type syncResult struct {
	Resource         string
	Count            int
	Err              error
	Warn             error
	Bounded          bool
	IntegrityFailure bool
	Duration         time.Duration
}

func newSyncCmd(flags *rootFlags) *cobra.Command {
	var resources []string
	var full bool
	var since string
	var concurrency int
	var dbPath string
	var maxPages int
	var latestOnly bool

	cmd := &cobra.Command{
		Use:   "sync",
		Short: "Sync API data to local SQLite for offline search and analysis",
		Long: `Sync data from the API into a local SQLite database. Supports resumable
incremental sync (only fetches new data since last sync) and full resync.
Once synced, use the 'search' command for instant full-text search.

Exit codes & warnings:
  Resources the API denies access to (HTTP 403, HTTP 400 with an
  access-policy body, or GraphQL errors carrying FORBIDDEN /
  UNAUTHENTICATED / PERMISSION_DENIED extensions) are reported as
  warnings rather than failing the run. In --json mode each is emitted
  as a {"event":"sync_warning",...} line carrying status, reason, and
  message fields, and a final {"event":"sync_summary",...} aggregates
  the run. The command exits non-zero only when every selected
  resource was access-denied or any resource hit a hard error.`,
		Example: `  # Sync all resources
  linear-pp-cli sync
  # Sync specific resources only
  linear-pp-cli sync --resources issues

  # Full resync (ignore previous checkpoint)
  linear-pp-cli sync --full

  # Parallel sync with 8 workers
  linear-pp-cli sync --concurrency 8

  # Latest-only: refresh head of each resource, no historical backfill
  linear-pp-cli sync --latest-only`,
		RunE: func(cmd *cobra.Command, args []string) error {
			// Validate input before opening the store or resetting a checkpoint.
			sinceTS := ""
			if since != "" {
				ts, err := parseSinceDuration(since)
				if err != nil {
					return fmt.Errorf("invalid --since value %q: %w", since, err)
				}
				sinceTS = ts.UTC().Format(time.RFC3339)
			}
			if maxPages < 0 {
				return fmt.Errorf("--max-pages must be non-negative")
			}
			if len(resources) == 0 {
				resources = defaultSyncResources()
			}
			defs := graphqlSyncDefs()
			for _, resource := range resources {
				if _, ok := defs[resource]; !ok {
					return fmt.Errorf("unknown resource %q", resource)
				}
			}

			c, err := flags.newClient()
			if err != nil {
				return err
			}
			c.NoCache = true

			if dbPath == "" {
				dbPath = defaultDBPath("linear-pp-cli")
			}

			db, err := store.OpenWithContext(cmd.Context(), dbPath)
			if err != nil {
				return fmt.Errorf("opening local database: %w", err)
			}
			defer db.Close()

			if cliutil.IsDogfoodEnv() && !cmd.Flags().Changed("max-pages") {
				maxPages = 1
			}

			// --latest-only: cap at page 1 and clear the resume cursor so
			// we fetch from the head. --since takes precedence when both
			// are set (historical context trumps latest-head).
			if latestOnly {
				if since == "" {
					maxPages = 1
				} else if humanFriendly {
					fmt.Fprintln(os.Stderr, "warning: --latest-only ignored because --since is set; --since takes precedence")
				}
			}

			// Reset only the resume position. Starting over is not a completed
			// attempt and must retain the last successful watermark and count.
			if full || (latestOnly && since == "") {
				for _, resource := range resources {
					_, _, count, err := db.GetSyncState(resource)
					if err != nil {
						return fmt.Errorf("reading sync state for %s: %w", resource, err)
					}
					if err := db.SaveSyncProgress(resource, "", count); err != nil {
						return fmt.Errorf("clearing sync cursor for %s: %w", resource, err)
					}
				}
			}

			// Worker pool: produce resources, N workers consume
			if concurrency < 1 {
				concurrency = 4
			}
			// Under PRINTING_PRESS_VERIFY=1 (mock/dry-run), all goroutines
			// reach SQLite without the natural serialization that network
			// latency provides in real syncs, so the worker pool races on
			// the writer and trips SQLITE_BUSY despite _busy_timeout.
			if cliutil.IsVerifyEnv() {
				concurrency = 1
			}

			started := time.Now()
			work := make(chan string, len(resources))
			results := make(chan syncResult, len(resources))

			var wg sync.WaitGroup
			for i := 0; i < concurrency; i++ {
				wg.Add(1)
				go func() {
					defer wg.Done()
					for resource := range work {
						res := syncResource(cmd.Context(), c, db, resource, sinceTS, full, maxPages, latestOnly && since == "")
						results <- res
					}
				}()
			}

			// Enqueue all resources
			for _, resource := range resources {
				work <- resource
			}
			close(work)

			// Collect results in a separate goroutine
			go func() {
				wg.Wait()
				close(results)
			}()

			var totalSynced int
			var errCount int
			var warnCount int
			var successCount int
			var firstErr error
			var firstPlaceholderErr error
			for res := range results {
				if res.Err != nil {
					if humanFriendly {
						fmt.Fprintf(os.Stderr, "  %s: error: %v\n", res.Resource, res.Err)
					}
					errCount++
					if firstErr == nil {
						firstErr = res.Err
					}
					if firstPlaceholderErr == nil && errors.Is(res.Err, client.ErrPlaceholderCredential) {
						firstPlaceholderErr = res.Err
					}
				} else if res.Warn != nil {
					if humanFriendly {
						fmt.Fprintf(os.Stderr, "  %s: warning: %v\n", res.Resource, res.Warn)
					}
					warnCount++
				} else {
					if humanFriendly {
						if res.Bounded {
							fmt.Fprintf(os.Stderr, "  %s: %d synced (requested limit reached; more pages remain)\n", res.Resource, res.Count)
						} else {
							fmt.Fprintf(os.Stderr, "  %s: %d synced (done)\n", res.Resource, res.Count)
						}
					}
					totalSynced += res.Count
					successCount++
				}
			}

			elapsed := time.Since(started)
			totalResources := successCount + warnCount + errCount
			if humanFriendly {
				if warnCount > 0 {
					fmt.Fprintf(os.Stderr, "Sync complete: %d records across %d resources (%d warned, %.1fs)\n",
						totalSynced, totalResources, warnCount, elapsed.Seconds())
				} else {
					fmt.Fprintf(os.Stderr, "Sync complete: %d records across %d resources (%.1fs)\n",
						totalSynced, totalResources, elapsed.Seconds())
				}
			} else {
				fmt.Fprintf(os.Stderr, `{"event":"sync_summary","total_records":%d,"resources":%d,"success":%d,"warned":%d,"errored":%d,"duration_ms":%d}`+"\n",
					totalSynced, totalResources, successCount, warnCount, errCount, elapsed.Milliseconds())
			}

			if errCount > 0 {
				if firstPlaceholderErr != nil {
					return classifyAPIError(cmd.OutOrStdout(), firstPlaceholderErr, flags)
				}
				return fmt.Errorf("%d resource(s) failed to sync", errCount)
			}
			if warnCount > 0 && successCount == 0 {
				return fmt.Errorf("%d resource(s) skipped due to insufficient access", warnCount)
			}
			return nil
		},
	}

	cmd.Flags().StringSliceVar(&resources, "resources", nil, "Comma-separated resource types to sync")
	cmd.Flags().BoolVar(&full, "full", false, "Full resync (ignore previous checkpoint)")
	cmd.Flags().StringVar(&since, "since", "", "Incremental sync duration (e.g. 7d, 24h, 1w, 30m)")
	cmd.Flags().IntVar(&concurrency, "concurrency", 4, "Number of parallel sync workers")
	cmd.Flags().StringVar(&dbPath, "db", "", "SQLite database file path (default: resolved data directory data.db)")
	cmd.Flags().IntVar(&maxPages, "max-pages", 0, "Maximum pages to fetch per resource (0 = unlimited)")
	cmd.Flags().BoolVar(&latestOnly, "latest-only", false, "Refresh head of each resource only; clears resume cursor and caps pages at 1. Mutually exclusive with --since (--since wins).")

	return cmd
}

// graphqlSyncDef describes how to sync a resource via GraphQL.
type graphqlSyncDef struct {
	Query       string // GraphQL forward-page query constant
	LatestQuery string // GraphQL backward-page query constant, when the schema supports last
	FieldPath   string // top-level field in the response data (e.g., "issues")
	PageSize    int    // default page size for this resource
}

// graphqlSyncDefs returns the sync definitions for all syncable resources.
func graphqlSyncDefs() map[string]graphqlSyncDef {
	return map[string]graphqlSyncDef{
		"issues": {
			Query:     client.IssuesListQuery,
			FieldPath: "issues",
			PageSize:  50,
		},
	}
}

// syncResource handles the full paginated sync of a single resource via GraphQL.
func syncResource(ctx context.Context, c *client.Client, db *store.Store, resource, sinceTS string, full bool, maxPages int, latestOnly bool) syncResult {
	started := time.Now()

	if !humanFriendly {
		fmt.Fprintf(os.Stderr, `{"event":"sync_start","resource":"%s"}`+"\n", resource)
	}

	defs := graphqlSyncDefs()
	def, ok := defs[resource]
	if !ok {
		return syncResult{Resource: resource, Err: fmt.Errorf("unknown resource %q", resource), Duration: time.Since(started)}
	}

	// Resume cursor from sync_state (unless --full cleared it)
	existingCursor, _, existingCount, stateErr := db.GetSyncState(resource)
	if stateErr != nil {
		return syncResult{Resource: resource, Err: stateErr, Duration: time.Since(started)}
	}
	// Invalidate readiness before any request, including requests that fail
	// before storing their first page. Keep the last lossless boundary.
	if err := db.SaveSyncProgress(resource, existingCursor, existingCount); err != nil {
		return syncResult{Resource: resource, Err: fmt.Errorf("saving sync progress for %s: starting attempt: %w", resource, err), Duration: time.Since(started)}
	}
	cursor := existingCursor
	progressCursor := existingCursor

	var totalCount int
	pagesFetched := 0
	// consumedTotal/extractFailureTotal feed the F4b symptom probe at end-
	// of-resource (rows extracted but none stored — likely an FTS5 trigger
	// failure or transaction rollback below the PK-extraction layer).
	// anomalyEmitted rate-limits per-resource warnings to one per sync run.
	consumedTotal := 0
	extractFailureTotal := 0
	anomalyEmitted := false
	capExitCursor := ""
	attemptComplete := false
	bounded := false
	incompleteReason := "pagination_end_unproven"
	pageSize := def.PageSize
	if pageSize <= 0 {
		pageSize = 50
	}

	for {
		variables := map[string]any{
			"first": pageSize,
		}
		if cursor != "" {
			variables["after"] = cursor
		}

		data, err := c.Query(ctx, def.Query, variables)
		if err != nil {
			if w, ok := isSyncAccessWarning(err); ok {
				if !humanFriendly {
					fmt.Fprintln(os.Stderr, syncWarningJSON(resource, "", w.Status, w.Reason, w.Message))
				}
				return syncResult{Resource: resource, Count: totalCount, Warn: fmt.Errorf("skipped due to insufficient access: %s (%s)", resource, w.Reason), Duration: time.Since(started)}
			}
			if !humanFriendly {
				fmt.Fprintln(os.Stderr, syncErrorJSON(resource, "", err))
			}
			return syncResult{Resource: resource, Count: totalCount, Err: fmt.Errorf("fetching %s: %w", resource, err), Duration: time.Since(started)}
		}
		if latestOnly && cursor == "" && def.LatestQuery != "" {
			latestData, err := c.Query(ctx, def.LatestQuery, map[string]any{"last": pageSize})
			if err != nil {
				return syncResult{Resource: resource, Count: totalCount, Err: fmt.Errorf("fetching latest page for %s: %w", resource, err), Duration: time.Since(started)}
			}
			data = chooseGraphQLLatestPage(def.FieldPath, data, latestData)
		}

		// Navigate to the connection field in the response
		var root map[string]json.RawMessage
		if err := json.Unmarshal(data, &root); err != nil {
			return syncResult{Resource: resource, Count: totalCount, Err: fmt.Errorf("parsing response for %s: %w", resource, err), Duration: time.Since(started)}
		}

		connRaw, ok := root[def.FieldPath]
		if !ok {
			// Try to find the field by scanning the response keys
			for k, v := range root {
				_ = k
				connRaw = v
				break
			}
			if connRaw == nil {
				incompleteReason = "missing_connection"
				break
			}
		}

		var conn struct {
			Nodes    []json.RawMessage `json:"nodes"`
			PageInfo struct {
				HasNextPage bool   `json:"hasNextPage"`
				EndCursor   string `json:"endCursor"`
			} `json:"pageInfo"`
		}
		if err := json.Unmarshal(connRaw, &conn); err != nil {
			return syncResult{Resource: resource, Count: totalCount, Err: fmt.Errorf("parsing connection for %s: %w", resource, err), Duration: time.Since(started)}
		}

		if len(conn.Nodes) == 0 {
			if !conn.PageInfo.HasNextPage {
				attemptComplete = true
				incompleteReason = ""
			} else {
				incompleteReason = "empty_page_with_continuation"
			}
			break
		}

		// Batch upsert all items from this page. UpsertBatch returns
		// (stored, extractFailures, err); the GraphQL path uses the same
		// store layer so it inherits the per-resource ID-field override
		// map and reduced fallback list automatically.
		stored, extractFailures, err := db.UpsertBatch(resource, conn.Nodes)
		if err != nil {
			if !humanFriendly {
				fmt.Fprintln(os.Stderr, syncErrorJSON(resource, "", err))
			}
			return syncResult{Resource: resource, Count: totalCount, Err: fmt.Errorf("upserting batch for %s: %w", resource, err), Duration: time.Since(started)}
		}
		// Emit at most one anomaly event per resource per sync run to avoid
		// log spam when extraction fails on every page. Order matches the
		// REST path (sync.go.tmpl): all-fail first, then partial-fail.
		if len(conn.Nodes) > 0 && stored == 0 && !anomalyEmitted {
			if humanFriendly {
				fmt.Fprintf(os.Stderr, "warning: %s returned %d items but stored 0 — the local store will be empty for this resource. Likely cause: scalar item shape rather than objects with extractable IDs.\n", resource, len(conn.Nodes))
			} else {
				fmt.Fprintf(os.Stderr, `{"event":"sync_anomaly","resource":"%s","consumed":%d,"stored":0,"reason":"all_items_failed_id_extraction"}`+"\n", resource, len(conn.Nodes))
			}
			anomalyEmitted = true
		} else if extractFailures > 0 && stored > 0 && !anomalyEmitted {
			if humanFriendly {
				fmt.Fprintf(os.Stderr, "warning: %s — could not extract a primary key for %d item(s); add x-resource-id to your spec.\n", resource, extractFailures)
			} else {
				fmt.Fprintf(os.Stderr, `{"event":"sync_anomaly","resource":"%s","count":%d,"reason":"primary_key_unresolved","message":"could not extract a primary key for %d item(s); add x-resource-id to your spec"}`+"\n", resource, extractFailures, extractFailures)
			}
			anomalyEmitted = true
		}

		consumedTotal += len(conn.Nodes)
		extractFailureTotal += extractFailures
		totalCount += stored
		if extractFailures > 0 {
			if err := db.SaveSyncProgress(resource, progressCursor, totalCount); err != nil {
				return syncResult{Resource: resource, Count: totalCount, Err: fmt.Errorf("saving sync progress for %s: %w", resource, err), Duration: time.Since(started)}
			}
			err := fmt.Errorf("%s dropped %d of %d item(s) without an extractable primary key", resource, extractFailures, len(conn.Nodes))
			return syncResult{Resource: resource, Count: totalCount, Err: err, IntegrityFailure: true, Duration: time.Since(started)}
		}
		if conn.PageInfo.EndCursor != "" {
			progressCursor = conn.PageInfo.EndCursor
		}

		// Progress reporting
		if humanFriendly {
			fmt.Fprintf(os.Stderr, "\r  %s: %d synced", resource, totalCount)
		} else {
			fmt.Fprintf(os.Stderr, `{"event":"sync_progress","resource":"%s","fetched":%d}`+"\n", resource, totalCount)
		}

		// Save resumable progress without advancing the completion watermark.
		if err := db.SaveSyncProgress(resource, progressCursor, totalCount); err != nil {
			return syncResult{Resource: resource, Count: totalCount, Err: fmt.Errorf("saving sync progress for %s: %w", resource, err), Duration: time.Since(started)}
		}

		pagesFetched++

		// Enforce page ceiling
		if maxPages > 0 && pagesFetched >= maxPages {
			capExitHasMore := conn.PageInfo.HasNextPage && conn.PageInfo.EndCursor != "" && conn.PageInfo.EndCursor != cursor
			bounded = capExitHasMore
			if bounded {
				incompleteReason = "max_pages_cap"
			}
			if !conn.PageInfo.HasNextPage {
				attemptComplete = true
				incompleteReason = ""
			}
			if capExitHasMore && !latestOnly {
				capExitCursor = conn.PageInfo.EndCursor
				incompleteReason = "max_pages_cap"
			}
			if capExitHasMore && !latestOnly && humanFriendly {
				fmt.Fprintf(os.Stderr, "\n  %s: reached --max-pages limit (%d pages, %d items)\n", resource, maxPages, totalCount)
			}
			break
		}

		// Check pagination
		if !conn.PageInfo.HasNextPage {
			attemptComplete = true
			incompleteReason = ""
			break
		}
		if conn.PageInfo.EndCursor == "" || conn.PageInfo.EndCursor == cursor {
			incompleteReason = "cursor_unavailable"
			break
		}

		cursor = conn.PageInfo.EndCursor
	}

	// F4b symptom probe: rows extracted successfully but none landed.
	// Likely cause is below the PK-extraction layer (FTS5 trigger,
	// transaction rollback, character encoding). Emits the symptom so
	// the next reproduction has a concrete starting point; does not
	// attempt to fix the root cause.
	if consumedTotal > 0 && totalCount == 0 && extractFailureTotal < consumedTotal {
		if humanFriendly {
			fmt.Fprintf(os.Stderr, "warning: %s — extracted %d items but stored 0; %d failed PK extraction. Suspect FTS5 trigger, rollback, or encoding.\n", resource, consumedTotal, extractFailureTotal)
		} else {
			fmt.Fprintf(os.Stderr, `{"event":"sync_anomaly","resource":"%s","consumed":%d,"extract_failures":%d,"reason":"stored_count_zero_after_extraction"}`+"\n", resource, consumedTotal, extractFailureTotal)
		}
		return syncResult{Resource: resource, Count: 0, Err: fmt.Errorf("%s consumed %d item(s) but stored 0 after primary-key extraction", resource, consumedTotal), IntegrityFailure: true, Duration: time.Since(started)}
	}

	// Only a proven natural end advances readiness. A capped or otherwise
	// unprovable walk retains a resume cursor and marks the latest attempt partial.
	if attemptComplete {
		if err := db.SaveSyncState(resource, "", totalCount); err != nil {
			return syncResult{Resource: resource, Count: totalCount, Err: fmt.Errorf("saving sync state for %s: %w", resource, err), Duration: time.Since(started)}
		}
	} else {
		if capExitCursor != "" {
			progressCursor = capExitCursor
		}
		if err := db.SaveSyncProgress(resource, progressCursor, totalCount); err != nil {
			return syncResult{Resource: resource, Count: totalCount, Err: fmt.Errorf("saving sync progress for %s: %w", resource, err), Duration: time.Since(started)}
		}
		if bounded {
			if !humanFriendly {
				fmt.Fprintf(os.Stderr, `{"event":"sync_partial","resource":"%s","total":%d,"reason":"%s"}`+"\n", resource, totalCount, incompleteReason)
			}
			return syncResult{Resource: resource, Count: totalCount, Bounded: true, Duration: time.Since(started)}
		}
		return syncResult{Resource: resource, Count: totalCount, Err: fmt.Errorf("%s sync incomplete (%s); completion watermark was not advanced", resource, incompleteReason), Duration: time.Since(started)}
	}

	if !humanFriendly {
		fmt.Fprintf(os.Stderr, `{"event":"sync_complete","resource":"%s","total":%d,"duration_ms":%d}`+"\n", resource, totalCount, time.Since(started).Milliseconds())
	}

	return syncResult{Resource: resource, Count: totalCount, Duration: time.Since(started)}
}

func chooseGraphQLLatestPage(fieldPath string, forwardData, backwardData json.RawMessage) json.RawMessage {
	forwardTime, forwardOK := newestGraphQLConnectionTimestamp(fieldPath, forwardData)
	backwardTime, backwardOK := newestGraphQLConnectionTimestamp(fieldPath, backwardData)
	if forwardOK && backwardOK && backwardTime.After(forwardTime) {
		if mergedData, ok := graphQLConnectionWithForwardPageInfo(fieldPath, forwardData, backwardData); ok {
			return mergedData
		}
		return backwardData
	}
	return forwardData
}

func graphQLConnectionWithForwardPageInfo(fieldPath string, forwardData, chosenData json.RawMessage) (json.RawMessage, bool) {
	var forwardRoot map[string]json.RawMessage
	if err := json.Unmarshal(forwardData, &forwardRoot); err != nil {
		return nil, false
	}
	forwardKey, forwardConnRaw := graphQLConnectionRaw(fieldPath, forwardRoot)
	if forwardKey == "" || forwardConnRaw == nil {
		return nil, false
	}
	var forwardConn map[string]json.RawMessage
	if err := json.Unmarshal(forwardConnRaw, &forwardConn); err != nil {
		return nil, false
	}
	pageInfo, ok := forwardConn["pageInfo"]
	if !ok {
		return nil, false
	}

	var chosenRoot map[string]json.RawMessage
	if err := json.Unmarshal(chosenData, &chosenRoot); err != nil {
		return nil, false
	}
	chosenKey, chosenConnRaw := graphQLConnectionRaw(fieldPath, chosenRoot)
	if chosenKey == "" || chosenConnRaw == nil {
		return nil, false
	}
	var chosenConn map[string]json.RawMessage
	if err := json.Unmarshal(chosenConnRaw, &chosenConn); err != nil {
		return nil, false
	}
	chosenConn["pageInfo"] = pageInfo
	connData, err := json.Marshal(chosenConn)
	if err != nil {
		return nil, false
	}
	chosenRoot[chosenKey] = connData
	mergedData, err := json.Marshal(chosenRoot)
	if err != nil {
		return nil, false
	}
	return mergedData, true
}

func graphQLConnectionRaw(fieldPath string, root map[string]json.RawMessage) (string, json.RawMessage) {
	if connRaw, ok := root[fieldPath]; ok {
		return fieldPath, connRaw
	}
	for key, connRaw := range root {
		return key, connRaw
	}
	return "", nil
}

func newestGraphQLConnectionTimestamp(fieldPath string, data json.RawMessage) (time.Time, bool) {
	var root map[string]json.RawMessage
	if err := json.Unmarshal(data, &root); err != nil {
		return time.Time{}, false
	}
	_, connRaw := graphQLConnectionRaw(fieldPath, root)
	if connRaw == nil {
		return time.Time{}, false
	}

	var conn struct {
		Nodes []json.RawMessage `json:"nodes"`
	}
	if err := json.Unmarshal(connRaw, &conn); err != nil {
		return time.Time{}, false
	}

	var newest time.Time
	var found bool
	for _, node := range conn.Nodes {
		nodeNewest, ok := newestJSONTimestamp(node)
		if !ok {
			continue
		}
		if !found || nodeNewest.After(newest) {
			newest = nodeNewest
			found = true
		}
	}
	return newest, found
}

func newestJSONTimestamp(data json.RawMessage) (time.Time, bool) {
	var value any
	if err := json.Unmarshal(data, &value); err != nil {
		return time.Time{}, false
	}
	return newestJSONValueTimestamp("", value)
}

func newestJSONValueTimestamp(fieldName string, value any) (time.Time, bool) {
	var newest time.Time
	var found bool
	switch v := value.(type) {
	case map[string]any:
		for k, child := range v {
			ts, ok := newestJSONValueTimestamp(k, child)
			if !ok {
				continue
			}
			if !found || ts.After(newest) {
				newest = ts
				found = true
			}
		}
	case []any:
		for _, child := range v {
			ts, ok := newestJSONValueTimestamp("", child)
			if !ok {
				continue
			}
			if !found || ts.After(newest) {
				newest = ts
				found = true
			}
		}
	case string:
		if isSyncTimestampField(fieldName) {
			ts, ok := parseSyncTimestamp(v)
			if ok {
				newest = ts
				found = true
			}
		}
	}
	return newest, found
}

func isSyncTimestampField(name string) bool {
	if name == "" {
		return false
	}
	normalized := strings.ToLower(strings.NewReplacer("_", "", "-", "").Replace(name))
	switch normalized {
	case "createdat", "updatedat", "publishedat", "modifiedat", "completedat", "closedat", "openedat", "startedat", "endedat", "expiresat", "timestamp", "datetime", "date", "time":
		return true
	}
	lower := strings.ToLower(name)
	return strings.HasSuffix(name, "At") ||
		strings.HasSuffix(lower, "_at") ||
		strings.HasSuffix(lower, "-at") ||
		strings.Contains(normalized, "timestamp") ||
		strings.HasSuffix(name, "Time") ||
		strings.HasSuffix(lower, "_time") ||
		strings.HasSuffix(lower, "-time") ||
		strings.HasSuffix(name, "Date") ||
		strings.HasSuffix(lower, "_date") ||
		strings.HasSuffix(lower, "-date")
}

func parseSyncTimestamp(value string) (time.Time, bool) {
	value = strings.TrimSpace(value)
	if value == "" {
		return time.Time{}, false
	}
	for _, layout := range []string{time.RFC3339Nano, time.RFC3339, "2006-01-02"} {
		ts, err := time.Parse(layout, value)
		if err == nil {
			return ts, true
		}
	}
	return time.Time{}, false
}

func defaultSyncResources() []string {
	return []string{
		"issues",
	}
}

// parseSinceDuration converts human-friendly duration strings into a time.Time.
func parseSinceDuration(s string) (time.Time, error) {
	re := regexp.MustCompile(`^(\d+)([dhwm])$`)
	matches := re.FindStringSubmatch(strings.TrimSpace(s))
	if matches == nil {
		return time.Time{}, fmt.Errorf("expected format like 7d, 24h, 1w, or 30m")
	}

	n, err := strconv.Atoi(matches[1])
	if err != nil {
		return time.Time{}, err
	}

	now := time.Now()
	switch matches[2] {
	case "d":
		return now.Add(-time.Duration(n) * 24 * time.Hour), nil
	case "h":
		return now.Add(-time.Duration(n) * time.Hour), nil
	case "w":
		return now.Add(-time.Duration(n) * 7 * 24 * time.Hour), nil
	case "m":
		return now.Add(-time.Duration(n) * time.Minute), nil
	default:
		return time.Time{}, fmt.Errorf("unknown unit %q", matches[2])
	}
}

// isSyncStatePersistenceError reports failures to persist sync checkpoints.
// Shared with workflow archive and the primary sync command's exit policy.
func isSyncStatePersistenceError(err error) bool {
	return err != nil && (strings.HasPrefix(err.Error(), "saving sync state for ") || strings.HasPrefix(err.Error(), "saving sync progress for "))
}
